/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as TryWorkspaceIdRouteImport } from './routes/try/$workspaceId'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSageRouteImport } from './routes/_layout/sage'
import { Route as LayoutPricingRouteImport } from './routes/_layout/pricing'
import { Route as LayoutOnboardingRouteImport } from './routes/_layout/onboarding'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutCouncilRouteImport } from './routes/_layout/council'
import { Route as LayoutCipherRouteImport } from './routes/_layout/cipher'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const TryWorkspaceIdRoute = TryWorkspaceIdRouteImport.update({
  id: '/try/$workspaceId',
  path: '/try/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSageRoute = LayoutSageRouteImport.update({
  id: '/sage',
  path: '/sage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPricingRoute = LayoutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOnboardingRoute = LayoutOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouncilRoute = LayoutCouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCipherRoute = LayoutCipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/cipher': typeof LayoutCipherRoute
  '/council': typeof LayoutCouncilRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/onboarding': typeof LayoutOnboardingRoute
  '/pricing': typeof LayoutPricingRoute
  '/sage': typeof LayoutSageRoute
  '/settings': typeof LayoutSettingsRoute
  '/try/$workspaceId': typeof TryWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/cipher': typeof LayoutCipherRoute
  '/council': typeof LayoutCouncilRoute
  '/history': typeof LayoutHistoryRoute
  '/items': typeof LayoutItemsRoute
  '/onboarding': typeof LayoutOnboardingRoute
  '/pricing': typeof LayoutPricingRoute
  '/sage': typeof LayoutSageRoute
  '/settings': typeof LayoutSettingsRoute
  '/try/$workspaceId': typeof TryWorkspaceIdRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/cipher': typeof LayoutCipherRoute
  '/_layout/council': typeof LayoutCouncilRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/onboarding': typeof LayoutOnboardingRoute
  '/_layout/pricing': typeof LayoutPricingRoute
  '/_layout/sage': typeof LayoutSageRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/try/$workspaceId': typeof TryWorkspaceIdRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/cipher'
    | '/council'
    | '/history'
    | '/items'
    | '/onboarding'
    | '/pricing'
    | '/sage'
    | '/settings'
    | '/try/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/cipher'
    | '/council'
    | '/history'
    | '/items'
    | '/onboarding'
    | '/pricing'
    | '/sage'
    | '/settings'
    | '/try/$workspaceId'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/cipher'
    | '/_layout/council'
    | '/_layout/history'
    | '/_layout/items'
    | '/_layout/onboarding'
    | '/_layout/pricing'
    | '/_layout/sage'
    | '/_layout/settings'
    | '/try/$workspaceId'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TryWorkspaceIdRoute: typeof TryWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/try/$workspaceId': {
      id: '/try/$workspaceId'
      path: '/try/$workspaceId'
      fullPath: '/try/$workspaceId'
      preLoaderRoute: typeof TryWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sage': {
      id: '/_layout/sage'
      path: '/sage'
      fullPath: '/sage'
      preLoaderRoute: typeof LayoutSageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pricing': {
      id: '/_layout/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LayoutPricingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/onboarding': {
      id: '/_layout/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutOnboardingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/council': {
      id: '/_layout/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof LayoutCouncilRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cipher': {
      id: '/_layout/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof LayoutCipherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutCipherRoute: typeof LayoutCipherRoute
  LayoutCouncilRoute: typeof LayoutCouncilRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOnboardingRoute: typeof LayoutOnboardingRoute
  LayoutPricingRoute: typeof LayoutPricingRoute
  LayoutSageRoute: typeof LayoutSageRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutCipherRoute: LayoutCipherRoute,
  LayoutCouncilRoute: LayoutCouncilRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOnboardingRoute: LayoutOnboardingRoute,
  LayoutPricingRoute: LayoutPricingRoute,
  LayoutSageRoute: LayoutSageRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TryWorkspaceIdRoute: TryWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
